config/routes.rb
Rails.application.routes.draw do

 resources :categories
  resources :cart_products
  devise_for :users
  resources :products
  resources :carts
  get '/search' => 'products#search', :as => 'search_page'
  
  root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total_price
    product.price * quantity
  end
  
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  include CurrentCart
  before_action :set_cart_product, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:create]

  def index
    @cart_products = CartProduct.all
  end

  def show
  end

  def new
    @cart_product = CartProduct.new
  end

  def edit
  end

  def create
    product = Product.find(params[:product_id])
    @cart_product = @cart.add_product(product)

      if @cart.save
        redirect_to @cart, notice: 'Item added to cart.'
      else
        render json: @cart.errors, status: :unprocessable_entity
      end
  end

  def update
      if @cart_product.update(cart_product_params)
        redirect_to @cart_product, notice: 'Product cart was successfully updated.'
      else
        render json: @cart_product.errors, status: :unprocessable_entity
      end
  end

  def destroy
    # find the current users cart id
    @cart = Cart.find(current_user.cart.id)
    @cart_product.destroy

    redirect_to products_path, notice: ' Product was successfully removed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_product
      @cart_product = CartProduct.find(params[:id])
    end

    def set_cart
      if !current_user.cart
        current_user.cart = Cart.new
      end
      @cart = current_user.cart
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_product_params
      params.require(:cart_product).permit(:product_id)
    end
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/_form.html.erb
<%= form_with(model: cart_product, local: true) do |form| %>
  <% if cart_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_product.errors.count, "error") %> prohibited this cart_product from being saved:</h2>

      <ul>
      <% cart_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :products_id %>
    <%= form.text_field :products_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cart_products/edit.html.erb
<h1>Editing Product Cart</h1>

<%= render 'form', cart_product: @cart_product %>

<%= link_to 'Show', @cart_product %> |
<%= link_to 'Back', cart_products_path %>

app/views/cart_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Carts</h1>

<table>
  <thead>
    <tr>
      <th>Products</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_products.each do |cart_product| %>
    <tr>
      <td><%= cart_product.products %></td>
      <td><%= cart_product.cart %></td>
      <td><%= link_to 'Show', cart_product %></td>
      <td><%= link_to 'Edit', edit_cart_product_path(cart_product) %></td>
      <td><%= link_to 'Destroy', cart_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cart_products/new.html.erb
<h1>New Product Cart</h1>

<%= render 'form', cart_product: @cart_product %>

<%= link_to 'Back', cart_products_path %>

app/views/cart_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Products:</strong>
  <%= @cart_product.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @cart_product.cart %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart_product) %> |
<%= link_to 'Back', carts_path %>