config/routes.rb
Rails.application.routes.draw do

 resources :categories
  resources :cart_products
  devise_for :users
  resources :products
  resources :carts
  get '/search' => 'products#search', :as => 'search_page'
  
  root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
belongs_to :user
has_many :products, dependent: :destroy

validates :category, presence: true

    def can_edit?(user)
        return user == self.user || user.has_role?(:admin)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authorise, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def index 
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    # if current user is the admin
    if user_signed_in? && current_user.has_role?(:admin) 
    category = Category.new(category_params)
    category.user = current_user
      if category.save
        flash[:alert] = "Your category has been saved"
        redirect_to categories_path
      else
        flash[:alert] = category.errors.full_messages.join('<br>')
        redirect_to new_category_path
      end
    end
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Product was successfully updated.'
    else
      render json: @category.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end
  
  private
  def set_category
    @category = Category.find(params[:id])
  end

  def authorise
    return if @category.can_edit?(current_user)

    flash[:alert] = "You are not authorised to perform that action!"
    redirect_to root_path
  end
  def category_params
    params.require(:category).permit(:category, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category, local: true do |f| %>

<% if category.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

  <ul>
    <% category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class='field'>
  <%= f.label :category %> <%= f.text_field :category %>
</div>
<div class='field'>
  <%= f.submit %>
</div>
<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/edit.html.erb
<h1>Edit a Category</h1>

<%= render "form", category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Categories (<%= @categories.count %>)</h1>
<table class='table'>
  <thead>
    <th>Category</th>
    <th>Added By</th>
  </thead>
  <tbody>
    <% @categories.each do |item| %>
    <tr>
      <td><%= item.category %></td>
      <td><%= item.user.email %></td>
      <!-- if current user is the owner of the product or the admin - show the edit and destroy paths -->
      <% if user_signed_in? && current_user.has_role?(:admin) %>
        <td><%= link_to 'Edit', edit_category_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<div><%= link_to 'Add a Category', new_category_path %></div>

app/views/categories/new.html.erb
<h1>Add a New Category</h1>


<%= render "form", category: @category %>


<div><%= link_to 'View Categories', categories_path %></div>

app/views/categories/show.html.erb
<h1 class='title'><%= @category.category %></h1>

        <section class='products'>
          <!-- show the products of the category id that matches the given category id -->
        <% Product.where(category_id: @category.id).each do |product| %>
          <ul class="results">
            <li class=''><%= link_to product.image.attached? ? image_tag(product.image, style: 'height: 200px') : '', product %> </li>
            <li class=''><strong><%= product.title %></li>
            <li class=''><%= product.description.first(50) %> <%= link_to '... Show More', product %></strong></li>
            <li class=''>Price: <%= number_to_currency(product.price) %></li>
            <li class=''>Condition: <%= product.condition %></li>
            <li class=''>Quantity: <%= product.quantity %></li>
            </ul>
          <% end %>
        </section>

        