config/routes.rb
Rails.application.routes.draw do

 resources :categories
  resources :cart_products
  devise_for :users
  resources :products
  resources :carts
  get '/search' => 'products#search', :as => 'search_page'
  
  root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
belongs_to :category
belongs_to :user
has_one_attached :image
has_many :cart_products, dependent: :destroy
has_many :carts, through: :cart_products
before_commit :add_default_img

validates :category, presence: true
validates :title, presence: true, length: { minimum: 5 }
validates :description, presence: true, length: { minimum: 200 }
validates :quantity, presence: true, :numericality => { :greater_than_or_equal_to => 1 }
validates :price, presence: true, :numericality => { :greater_than => 0 }

  # check if current user is the owner of the product or the admin
  def can_edit?(user)
    return user == self.user || user.has_role?(:admin)
  end

  def add_default_img
    unless image.attached? 
    self.image.attach(io: File.open(Rails.root.join("app", "assets", "images", "no-image-770x466.jpg")), filename: 'logo.png', content_type: "image/jpg")
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authorise, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  
  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.image.attach(product_params[:image])

    # add the current user to the product they have created
    @product.user = current_user
    
    # if current user is the admin
    if user_signed_in? && current_user.has_role?(:admin) 
      @product.condition = "New"
    elsif
      @product.condition = "Pre-owned"
    end

      if @product.save
        redirect_to @product, notice: 'Product was successfully created.'
      else
        flash[:alert] = @product.errors.full_messages.join('<br>')
        redirect_to new_product_path
      end
  end

  def update
      if @product.update(product_params)
        @product.image.attach(product_params[:image]) if product_params[:image] 
        redirect_to @product, notice: 'Product was successfully updated.'
      else
        flash[:alert] = @product.errors.full_messages.join('<br>')
        redirect_to @product 
      end
  end

  def destroy
    @product.destroy
      redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  def search
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
      # search all products title for the given search params
      @results = Product.all.where("lower(title) LIKE :search", search: "%#{@parameter}%") 
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def authorise
      return if @product.can_edit?(current_user)
  
      flash[:alert] = "You are not authorised to perform that action!"
      redirect_to root_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image, :quantity, :condition, :user_id, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
<% if product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

  <ul>
    <% product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div id='description' class="field" >
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>


<div class="field">
  <%= form.label :price %>
  <%= form.text_field :price %>
</div>

<div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>

<div class="field">
  <%= form.label :quantity %>
  <%= form.number_field :quantity %>
</div>

<div class="field">
  <%= form.label :category %>
  <%= collection_select(:product, :category_id, Category.all, :id, :category) %>
</div>

<div class="actions field">
  <%= form.submit %>
</div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class='title' >All Products</h1>

<div class='whole_grid'>
  <section id='products'>
    <% @products.each do |product| %>
    <ul class='listings'>
      <li><%= link_to product.image.attached? ? image_tag(product.image, style: 'height: 200px') : '', product %> </li>
      <li><strong><%= product.title %></li>
      <li><%= product.description.first(200) %> <%= link_to '... Show More', product %></strong></li>
      <li>Price: <%= number_to_currency(product.price) %></li>
      <li>Condition: <%= product.condition %></li>
      <li>Quantity: <%= product.quantity %></li>
      <!-- search Category for current products id then name of the category, direct to the products category with that id -->
      <li>Fandom: <%= link_to Category.find(product.category_id).category, category_path(product.category_id) %></li>
      <!-- if current user is the owner of the product or the admin - show the edit and destroy paths -->
      <% if user_signed_in? && product.can_edit?(current_user) %>
      <li class='button is-warning'><%= link_to 'Edit', edit_product_path(product) %></li>
      <li class='button is-danger'><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <% end %>
      </ul>
    <% end %>

    

</section>
</div>
<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<h1 class='title'>Search Results</h1>

  <section class='products'>
    <% @results.each do |result| %>
    <ul class='listings'>
      <li class=''><%= link_to result.image.attached? ? image_tag(result.image, style: 'height: 150px') : '', result %></li>
      <li><%= result.title %></li>
      <li><%= result.description.first(200) %><%= link_to '... Show More', result %></li>
      <li><%= number_to_currency(result.price) %></li>
      <% if user_signed_in? && result.can_edit?(current_user) %>
      <li class='button is-primary'><%= link_to 'Edit', edit_product_path(result) %></li>
      <li class='button is-danger'><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <% end %>
    </ul>
    <% end %>
  </section>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to @product.image.attached? ? image_tag(@product.image, width: 250) : '' %>
</p>


<p class='title'>
  <!-- <strong>Title:</strong> -->
  <%= @product.title %>
</p>

<p style="white-space: pre-line;">
  <!-- <strong>Description:</strong> -->
  <%= @product.description %>
</p>

<p>
  Check out more
  <strong><%= link_to Category.find(@product.category_id).category, category_path(@product.category_id) %></strong> merch!
  <!-- search Category for current products id then name of the category, direct to the products category with that id -->
</p>

<p>
  <strong>Condition:</strong>
  <%= @product.condition %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <% if @product.quantity >0 %>
  <strong>In Stock: </strong><%= @product.quantity %>
  <% elsif %>
  <strong>Out of Stock</strong>
  <% end %>
</p>

<section class=''>
  <p>
    <% if user_signed_in? %>
    <% if @product.quantity >0 %>
      <% if !@product.can_edit?(current_user) %>
    <div id="button"><%= button_to 'Add To Cart', cart_products_path(product_id: @product), class: 'button is-primary add-to-cart' %></div>
      <% end %>
    <% elsif %>
    <button class="button is-danger">Sold Out</button>
    <% end %>
    <% elsif  %>
    <div id="button"><%= button_to 'Sign In To Add To Cart', new_user_session_path, class: 'button is-primary' %></div>
    <% end %>
  </p>

  <p>
    <strong>Sold By: </strong><%= @product.user.email %>
  </p>

  <section>
      <% if user_signed_in? && @product.can_edit?(current_user) %>
      <div id="button"><%= link_to 'Edit', edit_product_path(@product), class: "button is-warning" %></div>
      <% end %>
      <div id="button"><%= link_to 'Back', products_path, class: "button is-info" %></div>
  </section>



    <!-- <p id="button" class="button is-info">
      <%= link_to 'Back', products_path %>
    </p> -->

  </section>