config/routes.rb
Rails.application.routes.draw do

 resources :categories
  resources :cart_products
  devise_for :users
  resources :products
  resources :carts
  get '/search' => 'products#search', :as => 'search_page'
  
  root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Geeky Exchange</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/7f842ba986.js" crossorigin="anonymous"></script>
</head>

<body>
  <header>
    <nav class="level container is-fluid">

      <p id='logo' , class="level-item">
        <%= link_to image_tag(image_path('logo.png')), products_path %>
      </p>

      <p class="level-item is-size-3" id='nav_product'>
        <% if user_signed_in? && current_user.has_role?(:admin) %>
        <%= link_to 'Add New Product', new_product_path %>
        <% elsif user_signed_in? && current_user.has_role?(:user) %>
        <%= link_to 'Add Pre-owned Product', new_product_path %>
        <% elsif %>
        <%= link_to 'Sign In', new_user_session_path %>
        <% end %>
      </p>

      <p class='level-item is-size-3'>
        <% if user_signed_in? && current_user.has_role?(:admin) %>
        <%= link_to 'Add a Category', new_category_path %>
        <% end %>
      </p>

      <p class='level-item is-size-3'>
        <% if user_signed_in? && current_user.has_role?(:admin) %>
        <%= link_to 'View Categories', categories_path %>
        <% end %>
      </p>

      <p class="level-item is-size-3">
        <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: 'delete' %>
        <% elsif %>
        <%= link_to 'Sign Up', new_user_registration_path %>
        <% end %>
      </p>

    </nav>
  </header>

  <section class='welcome'>
    <section class="container has-text-right">

      <p id="signin" class="is-size-5">
        <% if user_signed_in? %>
        Welcome, <%= current_user.email %>!
        <% end %>
      </p>

      <p class='cart'>
        <i class="fas fa-shopping-cart"></i>
        <% if user_signed_in? && current_user.cart %>
        <%= link_to "Shopping Cart", cart_path(current_user.cart) %>
        (<%= current_user.cart.total_quantity %>)
        <%= number_to_currency(current_user.cart.total_price) %>
        <% elsif %>
        <%= link_to "Shopping Cart", carts_path %>
        <% end %>
      </p>
      <p id='search' class='level'>
        <%= form_tag(search_page_path, :method => "get") do %>
        <%= search_field_tag :search, params[:search], placeholder: "Search Geeky Exchange" %>
        <%= button_tag 'Search', :name => nil %>
        <% end %>
      </p>
    </section>
  </section>

  <section id='fandombutton' class='level'>
    <!-- category name link to the path of that category -->
      <p class='level-item'><%= link_to Category.find(2).category, category_path(2) %></p>
      <p class='level-item'><%= link_to Category.find(3).category, category_path(3) %></p>
      <p class='level-item'><%= link_to Category.find(4).category, category_path(4) %></p>
      <p class='level-item'><%= link_to Category.find(7).category, category_path(7) %></p>
      <p class='level-item'><%= link_to Category.find(8).category, category_path(8) %></p>
      <p class='level-item'><%= link_to Category.find(9).category, category_path(9) %></p>
  </section>

  <div id='main' class="container">
    <p class="notice"><%= notice.html_safe if notice %></p>
    <p class="alert"><%= alert.html_safe if alert %></p>
    <%= yield %>
  </div>

  <footer id='footer'>
    <p>&copy Renee Nilsen 2019</p>
  </footer>

</body>

</html>